name: Run Telegram Bot
on:
  workflow_dispatch:   # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Auto-restart every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.8074930432:AAHzmRmuikXPegtamcA3ztqwcROEJLNC9sE }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          WHITELIST: ${{ secrets.WHITELIST }}  # Optional
        run: python bot.py
